config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  root 'home#index'

  resources :projects
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord

  validates :title, :presence => true
  validates :description, :presence => true


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, omniauth_providers: [:google_oauth2]


  def self.find_for_google_oauth2(access_token, signed_in_resource = nil)
    if access_token.info.email.end_with?('@gapintelligence.com')
      user = User.create_with(first_name: access_token.info.first_name, last_name: access_token.info.last_name, password: Devise.friendly_token[0, 20]).find_or_create_by(email: access_token.info.email)

      user
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def after_sign_out_path_for(user)
    root_path
  end

  protected
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < ApplicationController
  def google_oauth2
      # You need to implement the method below in your model (e.g. app/models/user.rb)
      @user = User.find_for_google_oauth2(request.env['omniauth.auth'], current_user)

      if @user
        sign_in_and_redirect @user, event: :authentication
      else
        redirect_to root_path, alert: 'Only gapintelligence.com emails are permitted.'
      end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to action: 'index', notice: 'Project was successfully created.' }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to action: 'index', notice: 'Project was successfully updated.' }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end

    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:title, :description, :notes, :status)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/omniauth_callbacks_helper.rb
module OmniauthCallbacksHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/home/index.html.slim
header
  h1.header-title Dev Day
  h3.header-subtitle Where gappers great ideas come to life
section.project-list
  .container
    .intro
      h3.section-title.grey What projects have we worked on so far?
    .intro.right
      a.call-button href="file:///Users/natashabelak-berger/Desktop/gapideas/projects.html"  Click Here
section.works
  .container
    h3.section-title.images Projects
    .column
      a href="http://highfive.gapintelligence.com" target="_blank"
        = image_tag "highfive.png"
    .column
      a href="http://goldenticket.gapintelligence.com" target="_blank"
        = image_tag "goldenticket.png"

  .container
    .column
      a href="http://storhaus.gapintelligence.com" target="_blank"
        = image_tag "storhaus.png"
    .column
      a href="file:///Users/natashabelak-berger/Desktop/gapideas/projects.html" target="_blank"
        = image_tag "andmore.png"
section.ideas
  .container
    .intro
      h3.ideas-title Do you have an idea you want a dev to check out?
    .intro.right
      .submit-button = link_to 'Submit Here', new_project_path

app/views/layouts/_messages.html.slim
- flash.each do |key, value|
  div class=("alert alert-#{key}")
    a.close data-dismiss="alert" href="#"  ×
    ul
      li
        = value

app/views/layouts/_navigation.html.slim
nav
  .nav
    .logo
      = image_tag "herbie.png"
    ul.menu
      li
        = link_to 'Home', root_path
      li
        = link_to 'Projects', projects_path
      li
        = link_to 'Submit Your Idea', new_project_path
      - if user_signed_in?
        = link_to "Log Out", destroy_user_session_path, :method => :delete
      

app/views/layouts/application.html.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type"
    title BadGapIdeas
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    = render 'layouts/navigation'
    = render 'layouts/messages'
    = yield

app/views/projects/_form.html.slim
.container
  = form_for @project do |f|
    - if @project.errors.any?
      #error_explanation
        h2 = "#{pluralize(@project.errors.count, "error")} prohibited this project from being saved:"
        ul
          - @project.errors.full_messages.each do |message|
            li = message
    .form-group.row
      .field
        = f.label :title
        = f.text_field :title
    .form-group.row
      .field
        = f.label :description
        = f.text_area :description
    .form-group.row
      .field
        = f.label :notes
        = f.text_area :notes
      .actions = f.submit

app/views/projects/_new_form.html.slim
.container
  = form_for @project do |f|
    - if @project.errors.any?
      #error_explanation
        h2 = "#{pluralize(@project.errors.count, "error")} prohibited this project from being saved:"
        ul
          - @project.errors.full_messages.each do |message|
            li = message
    .form-group.row
      .field
        = f.label :title
        = f.text_field :title, class: 'form-control'
    .form-group.row
      .field
        = f.label :description
        = f.text_area :description, class: 'form-control'
    .actions
      = f.submit 'Submit', class: 'btn btn-info'

app/views/projects/edit.html.slim
h1 Editing project

== render 'form'

=< link_to 'Back', projects_path

app/views/projects/index.html.slim
.container
  .row
    h1 Dev Day Project Ideas
  .row
    table.table.table-bordered
      thead
        tr
          th Title
          th Status
          th
          th

      tbody
        - @projects.each do |project|
          tr
            td = link_to project.title, project_path(project)
            td = project.status || "New"
            td = link_to 'Edit', edit_project_path(project)
            td = link_to 'Delete', project, data: { confirm: 'Are you sure?' }, method: :delete

app/views/projects/new.html.slim
.container
  .row
    h1 What do you want us to build?
  .row
    = render 'new_form'

app/views/projects/show.html.slim
p#notice = notice

p
  strong Title:
  = @project.title
p
  strong Description:
  = @project.description
p
  strong Notes:
  = @project.notes

=> link_to 'Edit', edit_project_path(@project)
'|
=< link_to 'Back', projects_path